typography_spectrum: 0.2869317608419806
color:
  brandStrength: 0.42809888860210776
  lightness: 0.45739590702578425
  saturation: 0.7188824987970293
  rhythmicContrast: 0.3892615200020373
  brandColors:
    - '#F9E4AD'
    - '#E6B098'
    - '#CC4452'
    - '#723147'
    - '#31152B'
layout_spectrum: 0.5359642873518169
name: reza
title: sail i go
